title: first principles
subtitle: reconstructive deconstruction
description: My personal home on the Web
name: Daniel Vijayakumar

remote_theme: dvijayak/jekyll-theme-dvijayak
layout: page

# Content & Editing
exclude: ["*.sublime-*"]
markdown: kramdown
excerpt_separator: <!--excerpt-->
collections:
  cis3000:
    output: true
    permalink: /:collection/:name

# Google Analytics
google_analytics: UA-155253485-1

plugins:
  - jekyll-sitemap
